version: 2.1

executors:
  default:
    docker:
      - image: cimg/python:3.9.5

orbs:
  python: circleci/python@1.4.0

workflows:
  main:
    jobs:
      - python/test:
          pkg-manager: poetry
          test-tool: pytest
