version: 2.1


orbs:
  python: circleci/python@1.4.0


workflows:
  main:
    jobs:
      - python/test:
          executor:
            name: python/default
            tag: 3.9.5
          args: "--dev"
          pkg-manager: poetry
          test-tool: pytest
