version: 2.1


orbs:
  python: circleci/python@1.4.0

jobs:
  test:
    executor:
      name: python/default
      tag: 3.9.5
    steps:
      - python/test:
          pkg-manager: poetry
          test-tool: pytest

workflows:
  main:
    jobs:
      - test
