version: 2.1

jobs:
  test:
    executor:
      name: python/default
      tag: 3.9.5
    steps:
      - python/test:
          pkg-manager: poetry
          test-tool: pytest

orbs:
  python: circleci/python@1.4.0

workflows:
  main:
    jobs:
      - python/test:
          pkg-manager: poetry
          test-tool: pytest
